### ISSUE TITLE
installation needs to be updated

### ISSUE THREAD

**Issue by SridharGS** [dzhou121/envim#2]
Hi @dzhou121 i pretty impressed with this repo. Waiting eagerly to get this done on my local. Right now i see https://github.com/dzhou121/envim/blob/master/index.js#L225 and this points to /Users/Lulu/go/src/tardis/transport/tcp.go can you please let me know what should install in my local and i am presently getting this error. 

![screen shot 2017-01-15 at 10 58 05 pm](https://cloud.githubusercontent.com/assets/8552839/21964649/27391352-db76-11e6-8655-1c1194db487b.png)

**Comment by dzhou121** [comment]
Hi @SridharGS Thank you for interest. 

You would need to build the PR locally. (you can clone my https://github.com/dzhou121/neovim on branch external-ui). 

For line https://github.com/dzhou121/envim/blob/master/index.js#L225, you need to change '/Users/Lulu/neovim/build/bin/nvim' into your locally built neovim binary, and you can remove the '/Users/Lulu/go/src/tardis/transport/tcp.go' bit, so that it becomes something like this:

var nvim_proc = spawn('your_local_nvim_binary_local_path', ['--embed'], {})

**Comment by SridharGS** [comment]
Thank you so much for your prompt response. Will message if it doesn't work.
